version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    commit-message:
      prefix: 'npm'
      include: 'scope'

  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
